name: Block Future Commits
description: A GitHub Action to ensure all commit timestamps are valid and do not exceed allowable limits (e.g., Y2K38).

branding:
  icon: "git-merge"
  color: "purple"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Validate commit timestamps
      run: |
        set -euo pipefail

        PR_COMMITS=$(git rev-list ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})

        CURRENT_DATE=$(date --utc +%s)
        YEAR_2038=$(date --utc --date="2038-01-19 03:14:07" +%s)

        for COMMIT in $PR_COMMITS; do
          COMMIT_DATE=$(git show -s --format=%ct "$COMMIT")

          echo $COMMIT_DATE

          if [ "$COMMIT_DATE" -gt "$YEAR_2038" ]; then
            echo "::error title=Invalid Commit Date::Commit $COMMIT has a timestamp exceeding the 2038 Unix limit."
            exit 1
          fi
        done

        echo "All commit timestamps are valid."
