name: Block Future Commits

on:
  pull_request:

jobs:
  validate-commit-timestamps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Commit Timestamps
        run: |
          set -euo pipefail

          PR_COMMITS=$(git rev-list ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})

          CURRENT_DATE=$(date --utc +%s)
          YEAR_2038=$(date --utc --date="2024-01-19 03:14:07" +%s)

          for COMMIT in $PR_COMMITS; do
            COMMIT_DATE=$(git show -s --format=%ct "$COMMIT")

            echo $COMMIT_DATE

            if [ "$COMMIT_DATE" -gt "$YEAR_2038" ]; then
              echo "::error title=Invalid Commit Date::Commit $COMMIT has a timestamp exceeding the 2038 Unix limit."
              exit 1
            fi
          done

          echo "All commit timestamps are valid."
