on: pull_request

name: Pull Request

jobs:
  message-check:
    name: Block Future Commits

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2

      - name: Block Future Commits
        uses: ./
