on: pull_request

name: Pull Request

jobs:
  message-check:
    name: Block Future Commits

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: $(( ${{ github.event_name == 'pull_request' && github.event.pull_request.commits || 0 }} + 1 ))

      - name: Block Future Commits
        uses: ./
